server:
  port: 8080

spring:
  application:
    name: mcp-boilerplate-java
  profiles:
    active: development
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  h2:
    console:
      enabled: true
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

mcp:
  require-auth: false
  jwt-secret: ${JWT_SECRET:your-secret-key-change-in-production}
  allowed-domains:
    - example.com
    - httpbin.org
    - jsonplaceholder.typicode.com
  max-file-size: 10485760 # 10MB
  rate-limit-requests: 100
  rate-limit-window: 3600
  allowed-directories:
    - /tmp
    - /var/tmp

logging:
  level:
    com.example.mcp: DEBUG
    org.springframework.web: INFO 